In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

# load Iris Data

In [2]:
iris = load_iris()

In [3]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

# Iris Data to Pandas DataFrame

In [4]:
df_X = pd.DataFrame(data=iris.data, columns = iris.feature_names)
df_Y = pd.DataFrame(data=iris.target, columns = ["target"])

In [5]:
df_X.sample(10, random_state=42)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
73                 6.1               2.8                4.7               1.2
18                 5.7               3.8                1.7               0.3
118                7.7               2.6                6.9               2.3
78                 6.0               2.9                4.5               1.5
76                 6.8               2.8                4.8               1.4
31                 5.4               3.4                1.5               0.4
64                 5.6               2.9                3.6               1.3
141                6.9               3.1                5.1               2.3
68                 6.2               2.2                4.5               1.5
82                 5.8               2.7                3.9               1.2

In [6]:
df_Y.sample(10, random_state=42)

     target
73        1
18        0
118       2
78        1
76        1
31        0
64        1
141       2
68        1
82        1

# (After 1차 Uplodad) git push 수정 테스트

In [7]:
df_Y.describe()

           target
count  150.000000
mean     1.000000
std      0.819232
min      0.000000
25%      0.000000
50%      1.000000
75%      2.000000
max      2.000000

In [8]:
df_X.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000